### ISSUE TITLE
Not working for Terminator

### ISSUE THREAD

**Issue by MarkOSullivan94** [widatama/vim-phoenix#1]
I've just tested this out for Terminator and I can't get the color scheme to work. If you've got it working for Terminator, could you provide instructions on how to do so?

**Comment by widatama** [comment]
Well, I have written in readme that there is no support for terminal yet :D

I am currently working on it, but it might not look as good as in gui because terminal color is limited.

In the meantime though, just use another colorscheme for terminal.

You can write something like this in your vimrc

``` viml
if has("gui_running")
  colorscheme phoenix
else
  colorscheme default
endif
```

**Comment by MarkOSullivan94** [comment]
Will be keeping an eye on this repo for further updates for Terminator :+1: 

Thanks
